# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

# specify branch build
trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    pip install git+https://github.com/tylunel/pvlib-python/all_changes#egg=pvlib
  displayName: 'Install pvlib'

- script: |
    pip install git+https://github.com/tylunel/pvpumpingsystem#egg=pvpumpingsystem
  displayName: 'Install pvpumpingsystem'

- script: |
    pip install git+https://github.com/tylunel/fluids#egg=fluids
  displayName: 'Install fluids'

- script: |
    pip install matplotlib sklearn tqdm
  displayName: 'Install dependencies'

#- script: |
#    pip install -r requirements.txt
#  displayName: 'Install dependencies'

#- script: |
#    python -m pip install flake8
#    flake8 --ignore=E226, E231, E241, E265, E266, F401, E741
#  displayName: 'Run lint tests'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'
